import type { EAItem, School } from "@/lib/dashboard-data"

const standardCommunity: EAItem[] = [
  { name: "Entry community", score: 67 },
  { name: "Community access", score: 0 },
  { name: "Heart of the school", score: 50 },
  { name: "Displays in public spaces", score: 50 },
  { name: "Educational signage", score: 50 },
  { name: "Access to water", score: 75 },
  { name: "Restroom location", score: 67 },
  { name: "Restrooms", score: 100 },
  { name: "Entrance accessibility", score: 62 },
]

const standardOrganization: EAItem[] = [
  { name: "Main office", score: 60 },
  { name: "Faculty collaboration", score: 75 },
  { name: "Staff lounge", score: 96 },
  { name: "Student support spaces", score: 96 },
  { name: "Instructional support spaces", score: 0 },
  { name: "Library location", score: 0 },
  { name: "Library adjacency", score: 50 },
  { name: "Academic neighborhoods", score: 0 },
  { name: "Storage", score: 0 },
]

/** Fully built-out school dashboards (Maplewood & Casis). */
export const detailedSchoolProfiles: School[] = [
  {
    id: "maplewood",
    name: "Maplewood Elementary",
    address: "3808 Maplewood Ave., Austin, TX 78722",
    age: 75,
    squareFootage: 62418,
    gradesServed: "PK-5",
    lat: 30.293176,
    lng: -97.714396,
    enrollment: 412,
    enrollmentDate: "Oct 2025",
    originalCapacity: 480,
    peCapacity: 506,
    utilOriginal: 86,
    utilPe: 81,
    nearby: [
      { name: "Campbell Elementary", type: "ES", distance: 0.74 },
      { name: "Kealing Middle School", type: "MS", distance: 1.12 },
      { name: "Blackshear Elementary", type: "ES", distance: 1.43 },
      { name: "McCallum High School", type: "HS", distance: 1.88 },
      { name: "Lee Elementary", type: "ES", distance: 2.05 },
    ],
    portfolio: [
      { label: "Enrollment", value: "412", ratio: 0.55, comparison: "vs. 540", badge: "2nd Quartile", color: "info" },
      { label: "Utilization", value: "81%", ratio: 0.81, comparison: "vs. 84%", badge: "1st Quartile", color: "good" },
      { label: "Educational Adequacy", value: "64.0%", ratio: 0.64, comparison: "vs. 71%", badge: "3rd Quartile", color: "info" },
      { label: "Space Sufficiency Score", value: "70%", ratio: 0.7, comparison: "Higher is better", color: "info", scaleNote: "Scale" },
      { label: "*Facility Condition Score", value: "0.24", ratio: 0.32, comparison: "Lower is better", color: "critical", scaleNote: "Scale" },
    ],
    totalNeedsLow: 8.41,
    totalNeedsHigh: 12.6,
    needsYear: 2031,
    systems: [
      { name: "HVAC", low: 2.01, high: 3.02, pctOfTotal: 24 },
      { name: "Electrical", low: 1.34, high: 2.01, pctOfTotal: 16 },
      { name: "Plumbing", low: 0.92, high: 1.38, pctOfTotal: 11 },
      { name: "Exterior Enclosure", low: 0.84, high: 1.26, pctOfTotal: 10 },
      { name: "Roofing", low: 0.76, high: 1.13, pctOfTotal: 9 },
      { name: "ADA Compliance", low: 0.67, high: 1.01, pctOfTotal: 8 },
      { name: "Site Improvements", low: 0.59, high: 0.88, pctOfTotal: 7 },
      { name: "Structure", low: 0.5, high: 0.75, pctOfTotal: 6 },
      { name: "Fire Protection", low: 0.34, high: 0.5, pctOfTotal: 4 },
      { name: "Conveying", low: 0.25, high: 0.38, pctOfTotal: 3 },
      { name: "Exterior Stairs", low: 0.17, high: 0.25, pctOfTotal: 2 },
    ],
    eaOverall: 64,
    eaCategories: [
      { name: "Presence", score: 77 },
      { name: "Safety & Security", score: 72 },
      { name: "Community", score: 62, items: standardCommunity },
      { name: "Organization", score: 67, items: standardOrganization },
      { name: "Classroom", score: 70 },
      { name: "Environmental Quality", score: 88 },
      { name: "Assembly", score: 41 },
      { name: "Extended Learning", score: 28 },
    ],
    spaceSufficiency: [
      { category: "Overall Campus", score: 70 },
      { category: "Administrative", score: 75 },
      { category: "Avg. Classroom", score: 100 },
      { category: "Gymnasium", score: 50 },
      { category: "Specialty Space", score: 50 },
      { category: "Student Support", score: 75 },
    ],
  },
  {
    id: "casis",
    name: "Casis Elementary",
    address: "2710 Exposition Blvd., Austin, TX 78703",
    age: 73,
    squareFootage: 88240,
    gradesServed: "PK-5",
    lat: 30.304354,
    lng: -97.765509,
    enrollment: 705,
    enrollmentDate: "Oct 2025",
    originalCapacity: 720,
    peCapacity: 760,
    utilOriginal: 98,
    utilPe: 93,
    nearby: [
      { name: "Bryker Woods Elementary", type: "ES", distance: 0.62 },
      { name: "O. Henry Middle School", type: "MS", distance: 0.95 },
      { name: "Austin High School", type: "HS", distance: 1.34 },
      { name: "Highland Park Elementary", type: "ES", distance: 1.71 },
      { name: "Mathews Elementary", type: "ES", distance: 2.18 },
    ],
    portfolio: [
      { label: "Enrollment", value: "705", ratio: 0.92, comparison: "vs. 540", badge: "4th Quartile", color: "good" },
      { label: "Utilization", value: "93%", ratio: 0.93, comparison: "vs. 84%", badge: "4th Quartile", color: "good" },
      { label: "Educational Adequacy", value: "71.0%", ratio: 0.71, comparison: "vs. 71%", badge: "2nd Quartile", color: "info" },
      { label: "Space Sufficiency Score", value: "82%", ratio: 0.82, comparison: "Higher is better", color: "good", scaleNote: "Scale" },
      { label: "*Facility Condition Score", value: "0.16", ratio: 0.21, comparison: "Lower is better", color: "warning", scaleNote: "Scale" },
    ],
    totalNeedsLow: 9.82,
    totalNeedsHigh: 14.73,
    needsYear: 2031,
    systems: [
      { name: "HVAC", low: 2.33, high: 3.5, pctOfTotal: 24 },
      { name: "Electrical", low: 1.56, high: 2.34, pctOfTotal: 16 },
      { name: "Plumbing", low: 1.07, high: 1.61, pctOfTotal: 11 },
      { name: "Exterior Enclosure", low: 0.97, high: 1.46, pctOfTotal: 10 },
      { name: "Roofing", low: 0.87, high: 1.31, pctOfTotal: 9 },
      { name: "ADA Compliance", low: 0.78, high: 1.17, pctOfTotal: 8 },
      { name: "Site Improvements", low: 0.68, high: 1.02, pctOfTotal: 7 },
      { name: "Structure", low: 0.58, high: 0.88, pctOfTotal: 6 },
      { name: "Fire Protection", low: 0.39, high: 0.58, pctOfTotal: 4 },
      { name: "Conveying", low: 0.29, high: 0.44, pctOfTotal: 3 },
      { name: "Exterior Stairs", low: 0.19, high: 0.29, pctOfTotal: 2 },
    ],
    eaOverall: 71,
    eaCategories: [
      { name: "Presence", score: 82 },
      { name: "Safety & Security", score: 79 },
      { name: "Community", score: 70, items: standardCommunity },
      { name: "Organization", score: 73, items: standardOrganization },
      { name: "Classroom", score: 76 },
      { name: "Environmental Quality", score: 91 },
      { name: "Assembly", score: 55 },
      { name: "Extended Learning", score: 44 },
    ],
    spaceSufficiency: [
      { category: "Overall Campus", score: 80 },
      { category: "Administrative", score: 80 },
      { category: "Avg. Classroom", score: 100 },
      { category: "Gymnasium", score: 75 },
      { category: "Specialty Space", score: 75 },
      { category: "Student Support", score: 80 },
    ],
  },
]
